package edu.harvard.canvas_data.client.tables;

import java.time.ZonedDateTime;
import java.util.ArrayList;
import java.util.List;

import org.apache.commons.csv.CSVRecord;

public class PseudonymDim extends CanvasDataTable {
  private Long id;
  private Long canvasId;
  private Long userId;
  private Long accountId;
  private String workflowState;
  private ZonedDateTime lastRequestAt;
  private ZonedDateTime lastLoginAt;
  private ZonedDateTime currentLoginAt;
  private String lastLoginIp;
  private String currentLoginIp;
  private Integer position;
  private ZonedDateTime createdAt;
  private ZonedDateTime updatedAt;
  private Boolean passwordAutoGenerated;
  private ZonedDateTime deletedAt;
  private String sisUserId;
  private String uniqueName;

  public PseudonymDim(final CSVRecord record) {
    String $id = record.get(0);
    if ($id != null && $id.length() > 0) {
      this.id = Long.valueOf($id);
    }
    String $canvasId = record.get(1);
    if ($canvasId != null && $canvasId.length() > 0) {
      this.canvasId = Long.valueOf($canvasId);
    }
    String $userId = record.get(2);
    if ($userId != null && $userId.length() > 0) {
      this.userId = Long.valueOf($userId);
    }
    String $accountId = record.get(3);
    if ($accountId != null && $accountId.length() > 0) {
      this.accountId = Long.valueOf($accountId);
    }
    this.workflowState = record.get(4);
    String $lastRequestAt = record.get(5);
    if ($lastRequestAt != null && $lastRequestAt.length() > 0) {
      this.lastRequestAt = ZonedDateTime.parse($lastRequestAt, CANVAS_DATA_TIMESTAMP_FORMAT);
    }
    String $lastLoginAt = record.get(6);
    if ($lastLoginAt != null && $lastLoginAt.length() > 0) {
      this.lastLoginAt = ZonedDateTime.parse($lastLoginAt, CANVAS_DATA_TIMESTAMP_FORMAT);
    }
    String $currentLoginAt = record.get(7);
    if ($currentLoginAt != null && $currentLoginAt.length() > 0) {
      this.currentLoginAt = ZonedDateTime.parse($currentLoginAt, CANVAS_DATA_TIMESTAMP_FORMAT);
    }
    this.lastLoginIp = record.get(8);
    this.currentLoginIp = record.get(9);
    String $position = record.get(10);
    if ($position != null && $position.length() > 0) {
      this.position = Integer.valueOf($position);
    }
    String $createdAt = record.get(11);
    if ($createdAt != null && $createdAt.length() > 0) {
      this.createdAt = ZonedDateTime.parse($createdAt, CANVAS_DATA_TIMESTAMP_FORMAT);
    }
    String $updatedAt = record.get(12);
    if ($updatedAt != null && $updatedAt.length() > 0) {
      this.updatedAt = ZonedDateTime.parse($updatedAt, CANVAS_DATA_TIMESTAMP_FORMAT);
    }
    String $passwordAutoGenerated = record.get(13);
    if ($passwordAutoGenerated != null && $passwordAutoGenerated.length() > 0) {
      this.passwordAutoGenerated = Boolean.valueOf($passwordAutoGenerated);
    }
    String $deletedAt = record.get(14);
    if ($deletedAt != null && $deletedAt.length() > 0) {
      this.deletedAt = ZonedDateTime.parse($deletedAt, CANVAS_DATA_TIMESTAMP_FORMAT);
    }
    this.sisUserId = record.get(15);
    this.uniqueName = record.get(16);
  }

  public Long getId() {
    return this.id;
  }

  public Long getCanvasId() {
    return this.canvasId;
  }

  public Long getUserId() {
    return this.userId;
  }

  public Long getAccountId() {
    return this.accountId;
  }

  public String getWorkflowState() {
    return this.workflowState;
  }

  public ZonedDateTime getLastRequestAt() {
    return this.lastRequestAt;
  }

  public ZonedDateTime getLastLoginAt() {
    return this.lastLoginAt;
  }

  public ZonedDateTime getCurrentLoginAt() {
    return this.currentLoginAt;
  }

  public String getLastLoginIp() {
    return this.lastLoginIp;
  }

  public String getCurrentLoginIp() {
    return this.currentLoginIp;
  }

  public Integer getPosition() {
    return this.position;
  }

  public ZonedDateTime getCreatedAt() {
    return this.createdAt;
  }

  public ZonedDateTime getUpdatedAt() {
    return this.updatedAt;
  }

  public Boolean getPasswordAutoGenerated() {
    return this.passwordAutoGenerated;
  }

  public ZonedDateTime getDeletedAt() {
    return this.deletedAt;
  }

  public String getSisUserId() {
    return this.sisUserId;
  }

  public String getUniqueName() {
    return this.uniqueName;
  }

  @Override
    public List<Object> getCsvFields() {
    final List<Object> fields = new ArrayList<Object>();
    fields.add(id);
    fields.add(canvasId);
    fields.add(userId);
    fields.add(accountId);
    fields.add(workflowState);
    fields.add(formatTimestamp(lastRequestAt));
    fields.add(formatTimestamp(lastLoginAt));
    fields.add(formatTimestamp(currentLoginAt));
    fields.add(lastLoginIp);
    fields.add(currentLoginIp);
    fields.add(position);
    fields.add(formatTimestamp(createdAt));
    fields.add(formatTimestamp(updatedAt));
    fields.add(passwordAutoGenerated);
    fields.add(formatTimestamp(deletedAt));
    fields.add(sisUserId);
    fields.add(uniqueName);
    return fields;
  }
}
